name: Deploying docuemntation to GitHub Pages

run-name: ${{ github.actor }} is deploying docuemntation to GitHub Pages ğŸš€

on:
  push:
    branches: [main]
    paths: |
      **/__stories__/*.@(mdx|js|jsx|mjs|ts|tsx)
  pull_request:
    branches: [main]
    paths: |
      **/__stories__/*.@(mdx|js|jsx|mjs|ts|tsx)

  workflow_dispatch:

jobs:
  build-and-deploy:
    permissions:
      contents: write

    runs-on: macos-latest

    steps:
      - name: Checkout ğŸ›ï¸
        uses: actions/checkout@v4
        with:
          ref: 'main'

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: ^9.6.0

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'
          cache: 'pnpm'

      - name: Install and Build ğŸ”§
        run: |
          CI=true pnpm install
          pnpm run build-storybook

      - name: Deploy for GitHub ğŸš€
        uses: JamesIves/github-pages-deploy-action@v4.6.1
        with:
          folder: storybook-static
          single-commit: true
